### ISSUE TITLE
Add public notification when phone is lost

### ISSUE THREAD

**Issue by x-real-ip** [x-real-ip/node-red#63]
https://companion.home-assistant.io/docs/notifications/notifications-basic/

```
automation:
  - alias: "Notify of Lost Device"
    trigger:
      ...
    action:
      - action: notify.mobile_app_<your_device_id_here>
        data:
          message: "This phone is lost, please return it to ..."
          data:
            visibility: public
```
